<a href="https://colab.research.google.com/github/Rabbi1067/Machine-Learning-ML-/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from sklearn.datasets import make_classification

Create a dataset

In [ ]:
X,y=make_classification(n_samples=1000, n_features=10,n_classes=2, n_informative=3, n_redundant=0, random_state=0)

In [ ]:

pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,-1.116345,-1.626999,0.536412,1.290064,-0.131588,-1.933002,-0.237657,0.645288,-1.509457,-0.394905
1,0.492717,1.206670,0.238648,-0.346497,0.958567,1.239356,0.404583,1.803750,-0.661116,1.408803
2,-0.302993,-0.316476,-0.352257,1.335580,-2.865006,-1.525519,1.042259,2.107367,-0.508119,-1.415068
3,0.732409,0.541953,0.628687,-0.612996,0.712131,-0.137752,1.617529,-1.735361,0.175727,1.102762
4,-0.205475,-1.515882,-2.363216,1.112195,-0.194596,0.314345,-0.707265,0.244997,-0.097668,0.178412
...,...,...,...,...,...,...,...,...,...,...
995,-0.718664,0.469762,-1.072811,0.965953,0.714875,0.985876,0.325146,0.104619,-0.721259,1.058192
996,0.085179,-2.410918,0.344840,-1.298156,0.402231,2.172120,-0.754590,0.937176,0.274149,-1.225963
997,-0.940735,0.418245,1.357435,0.997165,0.319156,0.016669,0.147306,-0.695560,-0.668690,2.503340
998,-0.027625,-1.441994,-0.170746,0.636213,-1.330688,2.231080,-1.263990,1.146268,1.503078,-1.032611


In [ ]:
y

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

Model train

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(x_train,y_train)

LogisticRegression()

Prediction for test data

In [ ]:
y_pred=logistic.predict(x_test)
print(y_pred)

[1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1 0 0 0 0 0 1 0
 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 1 1
 0 0 0 1 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0
 1 1 0 0 0 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0
 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0
 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 1
 0 1 1 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0 1
 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1
 1 0 0 0]


In [ ]:
logistic.predict_proba(x_test)

array([[0.31850325, 0.68149675],
       [0.40594779, 0.59405221],
       [0.20890943, 0.79109057],
       [0.08958864, 0.91041136],
       [0.21944611, 0.78055389],
       [0.18452415, 0.81547585],
       [0.84230836, 0.15769164],
       [0.37884088, 0.62115912],
       [0.39430041, 0.60569959],
       [0.40178764, 0.59821236],
       [0.79351856, 0.20648144],
       [0.43165691, 0.56834309],
       [0.32258159, 0.67741841],
       [0.4812937 , 0.5187063 ],
       [0.69577562, 0.30422438],
       [0.91441121, 0.08558879],
       [0.07308882, 0.92691118],
       [0.2843487 , 0.7156513 ],
       [0.77446641, 0.22553359],
       [0.90481558, 0.09518442],
       [0.01444169, 0.98555831],
       [0.47689358, 0.52310642],
       [0.86539583, 0.13460417],
       [0.34881772, 0.65118228],
       [0.53358047, 0.46641953],
       [0.11440607, 0.88559393],
       [0.49412736, 0.50587264],
       [0.89615543, 0.10384457],
       [0.33487874, 0.66512126],
       [0.42903122, 0.57096878],
       [0.

Perfromance matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report


array([[111,  34],
       [ 56,  99]])

In [ ]:
score = accuracy_score(y_test,y_pred)
print(score)  # final output
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7
[[111  34]
 [ 56  99]]
              precision    recall  f1-score   support

           0       0.66      0.77      0.71       145
           1       0.74      0.64      0.69       155

    accuracy                           0.70       300
   macro avg       0.70      0.70      0.70       300
weighted avg       0.71      0.70      0.70       300



**Hyperparameter Tuning And Cross Validation**

In [ ]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear','sag','saga']

In [ ]:
params=dict(penalty=penalty,C=c_values,solver=solver)

GridsearchCV

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
cv=RepeatedStratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,cv=5,scoring='accuracy',n_jobs=-1)
#grid.fit(x_train,y_train)

In [ ]:
grid

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'l1_ratio': [0.25, 0.5, 0.75, 1],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [ ]:
grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'l1_ratio': [0.25, 0.5, 0.75, 1],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [ ]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [ ]:
grid.best_score_

np.float64(0.7342857142857143)

In [ ]:
score = accuracy_score(y_test,y_pred)
print(score)  # final output
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7
[[111  34]
 [ 56  99]]
              precision    recall  f1-score   support

           0       0.66      0.77      0.71       145
           1       0.74      0.64      0.69       155

    accuracy                           0.70       300
   macro avg       0.70      0.70      0.70       300
weighted avg       0.71      0.70      0.70       300

