<a href="https://colab.research.google.com/github/Rabbi1067/Machine-Learning-ML-/blob/main/Numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🔹 Install

In [ ]:
#pip install numpy

Import

In [ ]:
import numpy as np

1D Array

In [ ]:
lst = [1,2,3,4]
arr=np.array(lst)
#print(arr)

In [ ]:
arr.shape

(4,)

In [ ]:
type(arr)

numpy.ndarray

2D Array (Matrix)

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


3D

In [ ]:
arr = np.array([[1, 2], [3, 4],[5,6]])
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
lst1=[1,2,3,4,5,6]
lst2=[7,8,9,10,11,12]
lst3=[13,14,15,16,17,18]
arr1=np.array([lst1,lst2,lst3])

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
arr1.shape

(3, 6)

Indexing

In [ ]:
arr[2]

array([5, 6])

In [ ]:
arr1[2]

array([13, 14, 15, 16, 17, 18])

In [ ]:
arr[2]=6

In [ ]:
arr

array([[1, 2],
       [3, 4],
       [6, 6]])

In [ ]:
arr[1:3]

array([[3, 4],
       [6, 6]])

Full array

In [ ]:
arr[::]

array([[1, 2],
       [3, 4],
       [6, 6]])

Full array with reverse

In [ ]:
arr[::-1]

array([[6, 6],
       [3, 4],
       [1, 2]])

2D array

In [ ]:
arr1[:,1]

array([ 2,  8, 14])

In [ ]:
arr1[1:,1:3]

array([[ 8,  9],
       [14, 15]])

EDA

In [ ]:
arr

array([[1, 2],
       [3, 4],
       [6, 6]])

In [ ]:
arr<2

array([[ True, False],
       [False, False],
       [False, False]])

In [ ]:
arr[arr<2]

array([1])

In [ ]:
arr1.shape

(3, 6)

In [ ]:
arr1.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

Mechanism to create an array

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
arr*arr

array([[ 1,  4],
       [ 9, 16],
       [36, 36]])

In [ ]:
arr1*arr1

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144],
       [169, 196, 225, 256, 289, 324]])

Ones

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Random Value

In [ ]:
np.random.randint(10,50)

48

In [ ]:
np.random.randint(10,50,4).reshape(2,2)

array([[21, 15],
       [19, 37]])

In [ ]:
np.random.randn(5,6)

array([[-0.17844441, -1.81489788, -1.32877865, -0.35110636,  0.09474719,
         0.04072509],
       [ 1.13243013,  0.22376794, -1.13449791, -1.1369196 , -1.23906048,
         1.43031969],
       [-0.09698633, -0.42652398, -1.41704706,  0.7703877 , -1.68543597,
         0.44500147],
       [-0.33722664,  0.05340716,  0.27266645,  0.47216782,  0.26759819,
         1.05301679],
       [-0.30827335,  1.07059217, -0.89357994,  0.35238702, -0.89460235,
         1.47529808]])